ros2 run move_turtlebot3 traj_square
ros2 run move_turtlebot3 traj_square
ros2 run move_turtlebot3 traj_square
ros2 run move_turtlebot3 traj_square
ros2 run move_turtlebot3 traj_square
ros2 run move_turtlebot3 traj_square
ros2 run move_turtlebot3 traj_square
ros2 run move_turtlebot3 traj_square
ros2 run move_turtlebot3 traj_square
ros2 run move_turtlebot3 traj_square
